# Generated by Django 5.2.17 on 2026-09-09 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperimentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_name", models.CharField(max_length=200)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("SYNTHETIC", "Synthetic"),
                            ("STABLE", "Stable"),
                            ("INTERVENTION", "Intervention"),
                            ("IMPULSE", "Impulse"),
                            ("MIXED_NOISE", "Mixed Noise"),
                            ("HIL", "Hil"),
                            ("REAL_WORLD", "Real World"),
                            ("CALIBRATION", "Calibration"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("REAL", "Real"),
                            ("SIMULATED", "Simulated"),
                            ("HIL", "Hil"),
                        ],
                        default="REAL",
                        max_length=12,
                    ),
                ),
                ("sensor_configuration", models.JSONField(blank=True, default=dict)),
                ("filter_version", models.CharField(blank=True, max_length=160)),
                (
                    "fpga_bitstream_version",
                    models.CharField(blank=True, max_length=160),
                ),
                ("firmware_version", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="FPGAImplementation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("report_source", models.CharField(blank=True, max_length=250)),
                ("clock_mhz", models.FloatField(blank=True, null=True)),
                ("max_clock_mhz", models.FloatField(blank=True, null=True)),
                ("timing_slack_ns", models.FloatField(blank=True, null=True)),
                ("power_w", models.FloatField(blank=True, null=True)),
                ("lut_used", models.FloatField(blank=True, null=True)),
                ("lut_available", models.FloatField(blank=True, null=True)),
                ("ff_used", models.FloatField(blank=True, null=True)),
                ("ff_available", models.FloatField(blank=True, null=True)),
                ("dsp_used", models.FloatField(blank=True, null=True)),
                ("dsp_available", models.FloatField(blank=True, null=True)),
                ("bram_used", models.FloatField(blank=True, null=True)),
                ("bram_available", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("sensor", models.CharField(blank=True, max_length=40)),
                ("event_type", models.CharField(max_length=40)),
                ("raw_value", models.FloatField(blank=True, null=True)),
                ("filtered_value", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="monitoring.experimentrun",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="implementation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="monitoring.fpgaimplementation",
            ),
        ),
        migrations.CreateModel(
            name="SensorSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("do_raw", models.FloatField(blank=True, null=True)),
                ("do_filtered", models.FloatField(blank=True, null=True)),
                ("do_reference", models.FloatField(blank=True, null=True)),
                ("do_software_reference", models.FloatField(blank=True, null=True)),
                ("do_fpga_code", models.BigIntegerField(blank=True, null=True)),
                ("do_software_code", models.BigIntegerField(blank=True, null=True)),
                ("ph_raw", models.FloatField(blank=True, null=True)),
                ("ph_filtered", models.FloatField(blank=True, null=True)),
                ("ph_reference", models.FloatField(blank=True, null=True)),
                ("ph_software_reference", models.FloatField(blank=True, null=True)),
                ("ph_fpga_code", models.BigIntegerField(blank=True, null=True)),
                ("ph_software_code", models.BigIntegerField(blank=True, null=True)),
                ("tds_raw", models.FloatField(blank=True, null=True)),
                ("tds_filtered", models.FloatField(blank=True, null=True)),
                ("tds_reference", models.FloatField(blank=True, null=True)),
                ("tds_software_reference", models.FloatField(blank=True, null=True)),
                ("tds_fpga_code", models.BigIntegerField(blank=True, null=True)),
                ("tds_software_code", models.BigIntegerField(blank=True, null=True)),
                ("temperature_raw", models.FloatField(blank=True, null=True)),
                ("temperature_filtered", models.FloatField(blank=True, null=True)),
                ("temperature_reference", models.FloatField(blank=True, null=True)),
                (
                    "temperature_software_reference",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "temperature_fpga_code",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "temperature_software_code",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("extra_sensors", models.JSONField(blank=True, default=dict)),
                ("sensor_status", models.JSONField(blank=True, default=dict)),
                ("reference_timestamp", models.DateTimeField(blank=True, null=True)),
                ("reference_source", models.CharField(blank=True, max_length=200)),
                ("fpga_latency_us", models.FloatField(blank=True, null=True)),
                ("fpga_cycles", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "quality_flag",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("SPIKE", "Spike"),
                            ("OUT_OF_RANGE", "Out Of Range"),
                            ("SENSOR_FAULT", "Sensor Fault"),
                            ("TRANSIENT", "Transient"),
                            ("NOISY", "Noisy"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "signal_state",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("NORMAL", "Normal"),
                            ("NOISY", "Noisy"),
                            ("TRANSIENT", "Transient"),
                            ("OUTLIER", "Outlier"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=12,
                    ),
                ),
                ("outlier_detected", models.BooleanField(default=False)),
                ("transient_detected", models.BooleanField(default=False)),
                ("ground_truth_spike", models.BooleanField(blank=True, null=True)),
                ("spike_removed", models.BooleanField(blank=True, null=True)),
                ("noise_estimate", models.FloatField(blank=True, null=True)),
                ("adaptive_threshold", models.FloatField(blank=True, null=True)),
                ("alpha_code", models.PositiveIntegerField(blank=True, null=True)),
                ("alpha_value", models.FloatField(blank=True, null=True)),
                ("packet_valid", models.BooleanField(default=True)),
                ("packet_crc_ok", models.BooleanField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("REAL", "Real"),
                            ("SIMULATED", "Simulated"),
                            ("HIL", "Hil"),
                        ],
                        default="REAL",
                        max_length=12,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="monitoring.experimentrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["run", "timestamp"],
                        name="monitoring__run_id_0ddc35_idx",
                    ),
                    models.Index(
                        fields=["run", "sequence_number"],
                        name="monitoring__run_id_0a9354_idx",
                    ),
                ],
            },
        ),
    ]
