# Generated by Django 5.2.17 on 2026-09-10 00:27

import django.core.validators
import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentrun",
            name="accumulator_q_format",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="alpha_noisy",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="alpha_normal",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="alpha_stable",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="alpha_transient",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="beta_noise",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="calibration_coefficients",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="calibration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="calibration_method",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="coefficient_q_format",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="dataset_sha256",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="experiment_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="fpga_clock_hz",
            field=models.FloatField(
                blank=True, null=True, validators=[monitoring.models.positive_frequency]
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="fpga_git_commit",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="gateway_git_commit",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="input_q_format",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="integrity_generated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="locked_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locked_experiments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="median_window",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="output_q_format",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="persistence_samples",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="reference_instrument",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="research_package_sha256",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="rounding_mode",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="sampling_rate_hz",
            field=models.FloatField(
                blank=True, null=True, validators=[monitoring.models.positive_frequency]
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="saturation_mode",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="sensor_model",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="software_git_commit",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="stm32_git_commit",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="threshold_base",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="threshold_multiplier",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="experimentrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("REAL", "Real"),
                    ("SIMULATED", "Simulated"),
                    ("HIL", "Hil"),
                    ("SYNTHETIC", "Synthetic"),
                ],
                default="REAL",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="experimentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("LOCKED", "Locked"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="sensorsample",
            name="source",
            field=models.CharField(
                choices=[
                    ("REAL", "Real"),
                    ("SIMULATED", "Simulated"),
                    ("HIL", "Hil"),
                    ("SYNTHETIC", "Synthetic"),
                ],
                default="REAL",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ExperimentUnlockAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("dataset_sha256", models.CharField(max_length=64)),
                ("research_package_sha256", models.CharField(max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlock_audit",
                        to="monitoring.experimentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-unlocked_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="HILReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor",
                    models.CharField(
                        choices=[
                            ("do", "Do"),
                            ("ph", "Ph"),
                            ("tds", "Tds"),
                            ("temperature", "Temperature"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sequence_number", models.PositiveBigIntegerField()),
                ("software_reference", models.FloatField(blank=True, null=True)),
                (
                    "software_integer_code",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("reference_source", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hil_references",
                        to="monitoring.experimentrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["run", "sensor"], name="monitoring__run_id_75c860_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "sensor", "sequence_number"),
                        name="hil_reference_unique_sequence",
                    )
                ],
            },
        ),
    ]
